version: "3.3"

services:
  bc1:
    build: .
    ports:
      - "8080:8080"

  bc2:
    build: .
    ports:
      - "8081:8080"

  bc3:
    build: .
    ports:
      - "8082:8080"

  bc4:
    build: .
    ports:
      - "8083:8080"

networks:
  default:
    name: bc_network
    driver: ipvlan
